/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.54
 * Generated at: 2021-12-06 03:51:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import review.ReviewDBBean;
import review.ReviewDataBean;
import java.text.SimpleDateFormat;
import board.BoardDBBean;
import board.BoardDataBean;
import java.util.List;
import java.util.ArrayList;

public final class boardList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("review.ReviewDataBean");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("review.ReviewDBBean");
    _jspx_imports_classes.add("board.BoardDataBean");
    _jspx_imports_classes.add("board.BoardDBBean");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Jua&family=Monoton&display=swap\" rel=\"stylesheet\">\n");
      out.write("<style>\n");
      out.write("@import url('https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap');\n");
      out.write("/*전체영역*/\n");
      out.write(":root { \n");
      out.write("		--line_color: #2c3e7e; \n");
      out.write("		--back_color: #f2f4fb;\n");
      out.write("}\n");
      out.write("a{text-decoration: none; color: var(--line_color); transition: .3s}\n");
      out.write("a:hover{ color:#99424f; transition: .3s}\n");
      out.write("#container{ width: 900px; margin: 20px auto;}\n");
      out.write(".btn { padding:10px; background: #b4baba; border: none; border-radius: 5px; font-family: 'Noto Sans KR', sans-serif; color: #; cursor: pinter; }\n");
      out.write(".btn:hover { background: #585555; transition: .5s}\n");
      out.write("/* 제목 */\n");
      out.write("#m_title { margin-bottom: 10px; font-size: 3em; text-align: center; font-family: 'Permanent Marker', cursive; }\n");
      out.write("#s_title { margin-bottom: 10px; font-size: 1.75em; font-weight: 900; font-family: 'Noto Sans KR', sans-serif; text-align: center;}\n");
      out.write("/* 로그인, 로그아웃 */\n");
      out.write("#d_login {display: flex; justify-content: right; gap:20px}\n");
      out.write("#d_id{color: #705e7b; cursor: pointer;}\n");
      out.write("#btn_logout{color:#99424f; cursor:pinter;}\n");
      out.write("\n");
      out.write("/* 검색  */\n");
      out.write("#d_search { text-align: center; margin-bottom: 10px }\n");
      out.write("#s_search { width: 100px; height: 25px; }\n");
      out.write("#i_search { width: 350px; height: 25px; }\n");
      out.write("#btn_search { width: 100px; height: 25px; background: #add5bd; border: 0;}\n");
      out.write("/* 테이블 */\n");
      out.write("table { width: 100%; border: 4px solid var(--line_color); border-collapse: collapse; border-left: hidden; border-right: hidden; color:var(--line_color)}\n");
      out.write("table .header{background: var(--back_color);}\n");
      out.write("td { border: 1px solid #000; }\n");
      out.write("tr { height: 50px; }\n");
      out.write("th,td { text-align: center; }\n");
      out.write("/* 페이징 처리 */\n");
      out.write("#paging { padding-top:10px; display: flex; gap:15px; justify-content: center;}\n");
      out.write("#paging div{width:17px; border-bottom: 1px solid #000; text-align: center;}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");

// 로그인을 했을 때 생성한 세션을 확인
String id = (String)session.getAttribute("memberId");
String pwd = (String)session.getAttribute("memberpwd");

if(id == null){
	out.print("<script>alert('로그인을 해주세요'); location = '../member/memberLoginForm.jsp'</script>");
}

// 페이지(pageing)처리 코드
int pageSize = 10; // 1개의 페이지에 10건의 게시글을 보여주는 변수
String pageNum = request.getParameter("pageNum");	// 페이지 번호를 클릭하여 이동할때 사용하는 변수 
if(pageNum == null) pageNum = "1"; 					// 페이지 번호가 없을 때, 로그인하여 게시글 페이지로 이동할 때

//DB 연동, 쿼리 실행
BoardDBBean boardPro = BoardDBBean.getInstance();

// 댓글 순서
int cnt = boardPro.getBoardListCount();

// 현재 페이지, 현재 페이지의 첫번째 행, 현재 페이지의 마지막 행
// 2페이지에서 10건, 11번부터 20번까지
int currentPage = Integer.parseInt(pageNum);
int startRow = (currentPage - 1) * pageSize + 1; // (2-1)*10 + 1 = 11 
int endRow = startRow + pageSize - 1;	// currentPage * pageSize, 11+10 == 20, 2*10 == 20

//날짜 포멧 설정
SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

/* List<BoardDataBean> boardList = boardPro.getBoardList(); */
List<BoardDataBean> boardList = null; 
if(cnt > 0){
	boardList = boardPro.getBoardList(currentPage, 10); // 클릭한 페이지의 데이터를 10개 가져온느 메소드 
}
// 각 페이지에 해당ㄹ하는 글의 역순 번호
// 전체가 167개, 2페이지에서는 157번부터 148번까지
int number = cnt - (currentPage - 1) * pageSize; 

      out.write("\n");
      out.write("\n");
      out.write("<div id=\"container\">\n");
      out.write("	<div id=\"m_title\">Street Woman Fighter</div>\n");
      out.write("	<div id=\"s_title\">커뮤니티 게시판</div>\n");
      out.write("	<div id=\"d_login\">\n");
      out.write("		<div id=\"d_id\"><a href=\"..\">");
      out.print(id );
      out.write("님</a></div>\n");
      out.write("		<div id=\"btn_logout\"><a href=\"../member/memberLogout.jsp\">로그아웃</a></div>\n");
      out.write("	</div>\n");
      out.write("	<div id=\"d_search\">\n");
      out.write("		<select name=\"s_search\" id=\"s_search\">\n");
      out.write("			<option>제목</option>\n");
      out.write("			<option>내용</option>\n");
      out.write("			<option>작성자</option>\n");
      out.write("		</select>\n");
      out.write("		<input type=\"search\" id=\"i_search\">\n");
      out.write("		<input type=\"button\" value=\"검색\" id=\"btn_search\">\n");
      out.write("	</div>\n");
      out.write("	<table>\n");
      out.write("		<tr class=\"header\">\n");
      out.write("			<th width=\"6%\">번호</th>\n");
      out.write("			<th width=\"58%\">제목</th>\n");
      out.write("			<th width=\"15%\">작성자</th>\n");
      out.write("			<th width=\"15%\">작성일</th>\n");
      out.write("			<th width=\"6%\">조회수</th>\n");
      out.write("		</tr>\n");
      out.write("<!-- 등록된 글이 없을 때  -->\n");
if(cnt == 0){ 
      out.write("	\n");
      out.write("		<tr><th colspan=\"5\">등록된 들이 없습니다.</th></tr>\n");
      out.write("<!-- 등록된 글이 있을때  -->\n");
} else { 			
		for(BoardDataBean board : boardList){ 
      out.write("\n");
      out.write("		<tr>\n");
      out.write("			<td>");
      out.print(number--  );
      out.write("</td>\n");
      out.write("			<td><a href=\"boardContent.jsp?num=");
      out.print(board.getNum());
      out.write('"');
      out.write('>');
      out.print(board.getSubject() );
      out.write("</a></td>\n");
      out.write("			<td>");
      out.print(board.getWriter() );
      out.write("</td>\n");
      out.write("			<td>");
      out.print(sdf.format(board.getRegdate()) );
      out.write("</td>\n");
      out.write("			<td>");
      out.print(board.getReadcount() );
      out.write("</td>\n");
      out.write("		</tr>\n");
      out.write("		");
}
	} 
      out.write("\n");
      out.write("	</table>\n");
      out.write("	<!-- 페이지 처리 영역 -->\n");
      out.write("	<div id=\"paging\">\n");
      out.write("	");

	if(cnt > 0){
		int startPage = 1;  // 시작페이지 번호
		int pageBlock = 10; // 노출하는 페이지 갯수
		// ex) 167건 데이터를 10건씩 보여주면 전체 페이지 객수 17개 , 160 -> 16개, 161~169까지는 17개
		int pageCount = cnt / pageSize + (cnt%pageSize == 0 ? 0 : 1); // 전체 페이지의 갯수
		
		// 시작 페이지 설정
		if(currentPage % 10 !=0) startPage = (currentPage/10) * 10 + 1;
		else startPage = (currentPage/10-1)*10;
		
		// 끝 페이지 설정
		int endPage  = startPage + pageBlock - 1;
		if(endPage > pageCount) endPage = pageCount;
		
		//이전 페이지 처리
		if(startPage>10){
			out.print("<div><a href='boardList.jsp?pageNum="+(startPage-10)+"'>◀</a></div>");
		}
		
		// 페이징 블럭 처리
		for(int i=startPage; i<=endPage; i++){
			out.print("<div><a href='boardList.jsp?pageNum="+ i +"'>"+ i +"</a></div>");
		}
		
		// 다음 페이지 처리
		if(endPage < pageCount){
			out.print("<div><a href='boardList.jsp?pageNum="+(startPage+10)+"'>▶</a></div>");
		}
	}
	
      out.write("\n");
      out.write("	</div>\n");
      out.write("</div> \n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
